### ISSUE TITLE
2 files

### ISSUE THREAD

**Issue by QuariX** [sbotor/gauss-blur#1]
Hello, help me pls , i need 2 files GaussBlurAsm.dll and GaussBlurC.dll

**Comment by sbotor** [comment]
Hi, I use this mostly for backup purposes so I never anticipated anyone coming here.

You should try changing the architecture to x64 in Visual Studio. The option should be between the Debug/Release drop down menu and the Run button, the default is probably set to Any CPU. Then try building the C# project by right clicking and choosing Build and see if all three projects get built.

**Comment by QuariX** [comment]
@sbotor  Thanks a lot, it really helped)

**Comment by sbotor** [comment]
No problem, keep in mind that a lot of stuff does not work yet as it is a project for my class and I work on it when I have the time
